### ISSUE TITLE
How to know if iterations are enough?

### ISSUE THREAD

**Issue by yfarjoun** [ChengtaoLi/dppnys_icml2016#2]
Hi,

I'm trying to use your DPP sampling code. is there a good way to know if I took "enough" iterations? is there a good rule of thumb to use? 

Thanks!

**Comment by yfarjoun** [comment]
hmmm. no. I get the following error:

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - keras
  - opencv

```

**Comment by yfarjoun** [comment]
:-(

**Comment by ChengtaoLi** [comment]
Hi, thanks for your interest in our work! 

1, All current ways in practice are empirical -- one way to do (as we did in our paper) is to monitor the values of objective and stop when it stays somewhat stable. 

2, What are you trying to do that causes this error? Is there any way I can help with?

**Comment by yfarjoun** [comment]
sorry about the keras comment. that was crossed threads.

**Comment by yfarjoun** [comment]
What objective do you use? the code doesn't (seem to) provide a straight forward way to findout the value of the determinant, and given that I'm working with 10,000 sized matrix (i.e. 10K x 10K) I don't want to calculate the determinanat naively....

**Comment by ChengtaoLi** [comment]
The objective is something that you are optimizing over, in our case for Nystrom the objective would be the matrix F-norm/2-norm of the difference between original matrix and the Nystrom approximation. 

It's true that the code doesn't provide a way to compute determinant because that is not needed in sampling from DPP. When you say you are working with 10,000-sized matrix, how many landmarks (the size of the subset) do you want to sample?

**Comment by yfarjoun** [comment]
right now, as a test, I'd like to go from 16K datapoints to about 8K. but in the future I'll need to go from 100K to 10K or so....

**Comment by ChengtaoLi** [comment]
I think what you can do is to use less datapoint, say, 2K, for checking whether the performance of Nystrom has converged. When you figure out the approximate number of iterations for convergence, run this number of iterations on your true test set.

**Comment by yfarjoun** [comment]
So the number of iterations should only be a function of what?
